##############################################
#                                            #
#              Catppuccin Theme              #
#                                            #
##############################################

# Catppuccin Latte Yellow
# This theme was created by: Catppuccin Org! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.
code_syntax_highlight = "catppuccin-latte"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#6c6f85"
full_screen_bg = "#eff1f5"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#1e66f5", "#8839ef"]

#-- File Panel
file_panel_fg = "#6c6f85"
file_panel_bg = "#eff1f5"
file_panel_border = "#9ca0b0"
file_panel_border_active = "#df8e1d"
file_panel_top_directory_icon = "#40a02b"
file_panel_top_path = "#1e66f5"
file_panel_item_selected_fg = "#df8e1d"
file_panel_item_selected_bg = "#eff1f5"

#-- Footer
footer_fg = "#6c6f85"
footer_bg = "#eff1f5"
footer_border = "#9ca0b0"
footer_border_active = "#df8e1d"

#-- Sidebar
sidebar_fg = "#6c6f85"
sidebar_bg = "#eff1f5"
sidebar_title = "#04a5e5"
sidebar_border = "#eff1f5"
sidebar_border_active = "#df8e1d"
sidebar_item_selected_fg = "#df8e1d"
sidebar_item_selected_bg = "#eff1f5"
sidebar_divider = "#9ca0b0"

#-- Modals
modal_fg = "#6c6f85"
modal_bg = "#eff1f5"
modal_border_active = "#9ca0b0"
modal_cancel_fg = "#ccd0da"
modal_cancel_bg = "#ea76cb"
modal_confirm_fg = "#ccd0da"
modal_confirm_bg = "#04a5e5"

#-- Help Menu
help_menu_hotkey = "#04a5e5"
help_menu_title = "#ea76cb"

#-- Special
cursor = "#dc8a78"
correct = "#40a02b"
error = "#d20f39"
hint = "#04a5e5"
cancel = "#ea76cb"
