##############################################
#                                            #
#              Catppuccin Theme              #
#                                            #
##############################################

# Catppuccin Frapp√© Yellow
# This theme was created by: Catppuccin Org! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.
code_syntax_highlight = "catppuccin-frappe"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a5adce"
full_screen_bg = "#303446"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#8caaee", "#ca9ee6"]

#-- File Panel
file_panel_fg = "#a5adce"
file_panel_bg = "#303446"
file_panel_border = "#737994"
file_panel_border_active = "#e5c890"
file_panel_top_directory_icon = "#a6d189"
file_panel_top_path = "#8caaee"
file_panel_item_selected_fg = "#e5c890"
file_panel_item_selected_bg = "#303446"

#-- Footer
footer_fg = "#a5adce"
footer_bg = "#303446"
footer_border = "#737994"
footer_border_active = "#e5c890"

#-- Sidebar
sidebar_fg = "#a5adce"
sidebar_bg = "#303446"
sidebar_title = "#99d1db"
sidebar_border = "#303446"
sidebar_border_active = "#e5c890"
sidebar_item_selected_fg = "#e5c890"
sidebar_item_selected_bg = "#303446"
sidebar_divider = "#737994"

#-- Modals
modal_fg = "#a5adce"
modal_bg = "#303446"
modal_border_active = "#737994"
modal_cancel_fg = "#414559"
modal_cancel_bg = "#f4b8e4"
modal_confirm_fg = "#414559"
modal_confirm_bg = "#99d1db"

#-- Help Menu
help_menu_hotkey = "#99d1db"
help_menu_title = "#f4b8e4"

#-- Special
cursor = "#f2d5cf"
correct = "#a6d189"
error = "#e78284"
hint = "#99d1db"
cancel = "#f4b8e4"
